feat(runtime): support swcli runtime build from multi sources
star-whale/starwhale pull request #2061
Opened 2023-04-07 11:56 UTC by tianweidut

## Description

## Modules
- [x] Client

## Checklist
- [ ] run code format and lint check
- [ ] add unit test
- [ ] add necessary doc

2023-04-11 08:00 UTC, tianweidut commented
@xuchuan  [5b290](https://github.com/star-whale/starwhale/pull/2061/commits/5b290b7883f0e3ff0adfd077be7e8838b0f599fa) commit hides the `--download-all-deps`, `--include-editable` and `--include-local-wheel` options for users.

2023-04-11 10:25 UTC, xuchuan requested changes

2023-04-11 10:25 UTC, xuchuan commented on client/starwhale/core/runtime/cli.py
> +    "--from-conda-name",
make options shorter, --conda --conda-prefix --venv --docker --yaml

2023-04-11 11:10 UTC, tianweidut commented on client/starwhale/core/runtime/cli.py
> +    "--from-conda-name",
got

2023-04-12 02:33 UTC, tianweidut commented
@xuchuan  updated:
1. simplify the command options:
   ```shell
            - from runtime.yaml:                                                                                                                                                                                                                                                    
          swcli runtime build  # use the current directory as the workdir and use the default runtime.yaml file                                                                                                                                                                   
          swcli runtime build -y example/pytorch/runtime.yaml # use example/pytorch/runtime.yaml as the runtime.yaml file                                                                                                                                                         
          swcli runtime build --yaml runtime.yaml # use runtime.yaml at the current directory as the runtime.yaml file                                                                                                                                                            
                                                                                                                                                                                                                                                                                  
          - from conda name:                                                                                                                                                                                                                                                                                                                                                                                                                   
          swcli runtime build --conda pytorch --name pytorch-runtime # use `pytorch-runtime` as the runtime name

          - from conda prefix path:
          swcli runtime build --conda-prefix /home/starwhale/anaconda3/envs/pytorch # get conda prefix path by `conda info --envs` command

          - from venv prefix path:
          swcli runtime build -venv /home/starwhale/.local/share/virtualenvs/pytorch --arch amd64

          - from docker image:
          swcli runtime build --docker pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime  # use the docker image as the runtime directly

          - from shell:
          swcli runtime build --shell --name pytorch-runtime # lock the current shell environment and use `pytorch-runtime` as the runtime name
   ```
2.  remove workdir option for `build` command

2023-04-13 02:21 UTC, xuchuan approved these changes
LGTM

2023-04-13 02:21 UTC, merged