enhance(controller): support baidu oss offical sdk
star-whale/starwhale pull request #2519
Opened 2023-07-18 06:18 UTC by jialeicui

## Description

## Modules
- [ ] UI
- [ ] Controller
- [ ] Agent
- [ ] Client
- [ ] Python-SDK
- [ ] Others

## Checklist
- [ ] run code format and lint check
- [ ] add unit test
- [ ] add necessary doc

2023-07-18 06:37 UTC, xuchuan requested changes

2023-07-18 06:37 UTC, xuchuan commented on server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/baidu/StorageAccessServiceBos.java
> +    private final BosClient ossClient;
bosClient

2023-07-18 07:42 UTC, jialeicui commented on server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/baidu/StorageAccessServiceBos.java
> +    private final BosClient ossClient;
Done

2023-07-21 05:50 UTC, anda-ren approved these changes
LGTM

2023-07-21 05:50 UTC, anda-ren commented on server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/baidu/StorageAccessServiceBos.java
> +    private boolean isNotFount(BceServiceException e) {
typo for Found?

2023-07-21 07:57 UTC, jialeicui commented on server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/baidu/StorageAccessServiceBos.java
> +    private boolean isNotFount(BceServiceException e) {
Done

2023-07-25 02:55 UTC, anda-ren approved these changes
LGTM

2023-08-01 11:08 UTC, xuchuan approved these changes

2023-08-01 11:08 UTC, merged