add dataset name in swds input.json
star-whale/starwhale pull request #264
Opened 2022-05-07 08:42 UTC by anda-ren

## Description
- add dataset name in swds input.json
## Modules
- [ ] UI
- [x] Controller
- [x] Agent
- [ ] Client
- [x] Python-SDK
- [ ] Others

## Checklist
- [ ] run code format and lint check
- [ ] add unit test
- [x] add necessary doc

2022-05-07 08:53 UTC, tianweidut requested changes
others lgtm

2022-05-07 08:53 UTC, tianweidut commented on client/starwhale/api/_impl/loader.py
> +                self._do_iter(_swds["bucket"], _swds["key"]["data"], _swds["ext_attr"]),
`_swds.get('ext_attr', {})`

2022-05-07 08:53 UTC, tianweidut commented on client/starwhale/api/_impl/model.py
> +                    ds_name=data.ext_attr["ds_name"], ds_version=data.ext_attr["ds_version"])
`data.ext_attr.get('ds_name', "")`

2022-05-09 02:05 UTC, goldenxinxing approved these changes
lgtm

2022-05-09 02:26 UTC, goldenxinxing approved these changes
lgtm

2022-05-09 02:31 UTC, tianweidut approved these changes
LGTM

2022-05-09 02:31 UTC, merged