s3 storage implementation/ index loading/ task & job status management/
star-whale/starwhale pull request #39
Opened 2022-03-30 10:25 UTC by anda-ren

## Description
- s3 storage implementation
- index loading
- task & job status management
## Modules
- [ ] UI
- [X] Controller
- [ ] Agent
- [ ] Client
- [ ] Python-SDK
- [X] Others

## Checklist
- [x] run code format and lint check
- [ ] add unit test
- [x] add necessary doc

2022-03-30 10:34 UTC, dreamlandliu submitted a review, later dismissed
LGTM

2022-03-30 10:39 UTC, tianweidut requested changes

2022-03-30 10:39 UTC, tianweidut commented on server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlock.java
> + *    "id": 1,          //第n条记录
use English comment？

2022-03-30 10:39 UTC, tianweidut commented on server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
> +                .currentTransactionStatus();
```TransactionAspectSupport.currentTransactionStatus();```
in one line?

2022-03-31 02:13 UTC, anda-ren commented on server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
> +                .currentTransactionStatus();
done

2022-03-31 02:26 UTC, goldenxinxing approved these changes
LGTM

2022-03-31 02:33 UTC, tianweidut approved these changes
LGTM

2022-03-31 02:34 UTC, merged